language: php
php:
  - '7.0'
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - travis_retry composer self-update
before_script: travis_retry composer install
script:
  -  mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
  - travis_retry php vendor/bin/coveralls -v