language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - travis_retry composer self-update
before_script: travis_retry composer install
script: vendor/bin/phpunit